version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` and `clamav` directory
    directories: ["/", "/clamav"]
    # Check for updates once a week
    schedule:
      interval: "weekly"
