replicaCount: 1

image:
  repository: 'set by ci/cd'
  tag: 'set by ci/cd' # pragma: allowlist secret
  pullPolicy: Always

priorityClassName: ""

imagePullSecrets: []

nameOverride: clamav
fullnameOverride: clamav

podSecurityContext:
securityContext:

service:
  type: ClusterIP
  port: 3310

# Ensure to have the minimum resources to run clamd
resources:
  requests:
    cpu: 1000m
    memory: 3Gi

nodeSelector: {}

tolerations: []

affinity: {}

affinityTemplate: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchLabels: {{ include "clamav.selectorLabels" . | nindent 10 }}

startupProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 3
  timeoutSeconds: 600

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 600

readinessProbe:
  initialDelaySeconds: 90
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 600

hpa:
  enabled: false
  maxReplicas: 5
  # average CPU usage utilization percentage per pod (1-100)
  cpu: 80
  # average Memory usage utilization percentage per pod (1-100)
  # memory: 80
  # average http_requests utilization per pod (value as a string)
  # requests: 1k

podDisruptionBudget:
  enabled: true
  minAvailable: 1
  # maxUnavailable: 1

## Clamav data dir persistence
persistentVolume:
  ## If true, a Persistent Volume Claim is created, otherwise it uses an emptyDir
  ##
  enabled: true

  annotations: {}
  accessModes:
  - ReadWriteOnce
  size: 4Gi
  storageClass: netapp-block-standard

configVersion: "1.0"
