apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpi-app
  labels:
    app.kubernetes.io/name: vpi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: vpi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpi-app
    spec:
      containers:
        - name: vpi-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
