apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpi-app
  labels:
    app.kubernetes.io/name: vpi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: vpi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpi-app
    spec:
      containers:
        - name: vpi-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: visitz-api-config
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_SECRET
            - name: CLAMD_HOST
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLAMD_HOST
            - name: CLAMD_PORT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLAMD_PORT
            - name: CA_CERT
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: CA_CERT
            - name: SERVER_CERT
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: SERVER_CERT
            - name: SERVER_KEY
              valueFrom:
                secretKeyRef:
                    name: mutual-authentication-mtls
                    key: SERVER_KEY
            - name: VPI_APP_LABEL
              value: {{ .Values.vpiAppBuildLabel.version }}
            - name: VPI_APP_ENV
              value: {{ .Values.vpiAppEnv }}
      restartPolicy: Always
