apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpi-app
  labels:
    app.kubernetes.io/name: vpi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: vpi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpi-app
    spec:
      containers:
        - name: vpi-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: NODE_ENV
            - name: RECORD_CACHE_MS
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: RECORD_CACHE_MS
            - name: UPSTREAM_BASE_URL
              value: {{ .Values.upstream.baseUrl }}
            - name: SUPPORT_NETWORK_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SUPPORT_NETWORK_ENDPOINT
            - name: CASE_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_ENDPOINT
            - name: INCIDENT_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_ENDPOINT
            - name: SR_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SR_ENDPOINT
            - name: MEMO_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: MEMO_ENDPOINT
            - name: ACCESS_TOKEN_URL
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: ACCESS_TOKEN_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_SECRET
            - name: SKIP_AUTH_GUARD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SKIP_AUTH_GUARD
            - name: SKIP_JWT_CACHE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SKIP_JWT_CACHE
            - name: IN_PERSON_VISITS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: IN_PERSON_VISITS_ENDPOINT
            - name: ATTACHMENTS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: ATTACHMENTS_ENDPOINT
            - name: IN_PERSON_VISITS_POST_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: IN_PERSON_VISITS_POST_ENDPOINT
            - name: CASE_CONTACTS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_CONTACTS_ENDPOINT
            - name: INCIDENT_CONTACTS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_CONTACTS_ENDPOINT
            - name: SR_CONTACTS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SR_CONTACTS_ENDPOINT
            - name: MEMO_CONTACTS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: MEMO_CONTACTS_ENDPOINT
            - name: CASE_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_WORKSPACE
            - name: INCIDENT_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_WORKSPACE
            - name: SR_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SR_WORKSPACE
            - name: MEMO_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: MEMO_WORKSPACE
            - name: SUPPORT_NETWORK_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SUPPORT_NETWORK_WORKSPACE
            - name: IN_PERSON_VISITS_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: IN_PERSON_VISITS_WORKSPACE
            - name: ATTACHMENTS_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: ATTACHMENTS_WORKSPACE
            - name: IN_PERSON_VISITS_POST_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: IN_PERSON_VISITS_POST_WORKSPACE
            - name: CONTACTS_WORKSPACE
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CONTACTS_WORKSPACE
            - name: CASE_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_IDIR_FIELD
            - name: INCIDENT_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_IDIR_FIELD
            - name: SR_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SR_IDIR_FIELD
            - name: MEMO_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: MEMO_IDIR_FIELD
            - name: CASE_SINCE_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_SINCE_FIELD
            - name: CASE_SEARCHSPEC_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_SEARCHSPEC_IDIR_FIELD
            - name: CASE_RESTRICTED_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_RESTRICTED_FIELD
            - name: INCIDENT_SINCE_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_SINCE_FIELD
            - name: INCIDENT_SEARCHSPEC_IDIR_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_SEARCHSPEC_IDIR_FIELD
            - name: INCIDENT_RESTRICTED_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_RESTRICTED_FIELD
            - name: CASE_TYPE_FIELD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_TYPE_FIELD
            - name: VPI_APP_LABEL
              value: {{ .Values.vpiAppBuildLabel.version }}
            - name: VPI_APP_ENV
              value: {{ .Values.vpiAppEnv }}
      restartPolicy: Always
