apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpi-app
  labels:
    app.kubernetes.io/name: vpi-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: vpi-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vpi-app
    spec:
      containers:
        - name: vpi-app-container
          image: "{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: NODE_ENV
            - name: RECORD_CACHE_MS
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: RECORD_CACHE_MS
            - name: UPSTREAM_BASE_URL
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: UPSTREAM_BASE_URL
            - name: SUPPORT_NETWORK_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SUPPORT_NETWORK_ENDPOINT
            - name: CASE_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CASE_ENDPOINT
            - name: INCIDENT_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: INCIDENT_ENDPOINT
            - name: SR_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SR_ENDPOINT
            - name: MEMO_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: MEMO_ENDPOINT
            - name: ACCESS_TOKEN_URL
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: ACCESS_TOKEN_URL
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: CLIENT_SECRET
            - name: IN_PERSON_VISITS_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: IN_PERSON_VISITS_ENDPOINT
            - name: VPI_APP_LABEL
              value: {{ .Values.vpiAppBuildLabel.version }}
            - name: SKIP_AUTH_GUARD
              valueFrom:
                secretKeyRef:
                    name: visitz-api
                    key: SKIP_AUTH_GUARD
            - name: VPI_APP_LABEL
              value: {{ .Values.vpiAppBuildLabel.version }}
      restartPolicy: Always
