replicaCount: 1
 
image:
  repository: ghcr.io/bcgov/visitz-api
  tag: '<set by CI/CD>'
  pullPolicy: Always
 
service:
  type: ClusterIP
  port: 443
 
resources: {}
 
nodeSelector: {}
 
tolerations: []
 
affinity: {}
