name: ClamAV Build and Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - tools
    

env:
  HELM_RELEASE_NAME: clamav-deployment
  REGISTRY: ghcr.io
  IMAGE_NAME: "clamav:${{ github.repository }}"
  HUSKY: 0

jobs:

  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./clamav
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build_and_push
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: 'YAML poke: Set image tag'
        uses: fjogeleit/yaml-update-action@v0.15.0
        with:
          valueFile: 'clamav/values.yaml'
          propertyPath: 'clamav.tag'
          value: ${{ github.event.inputs.environment }}
          commitChange: false

      - name: 'YAML poke: Set image location'
        uses: fjogeleit/yaml-update-action@v0.15.0
        with:
          valueFile: 'clamav/values.yaml'
          propertyPath: 'clamav.image'
          value: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          commitChange: false

      - name: Authenticate with OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          namespace: ${{ secrets.TOOLS_OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.TOOLS_OPENSHIFT_SERVICE_ACCOUNT_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./clamav \
            --namespace ${{ secrets.TOOLS_OPENSHIFT_NAMESPACE }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ needs.build_and_push.outputs.image_tag }}
