name: ClamAV Build and Deploy
permissions:
  contents: read
  deployments: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - tools
    

env:
  HELM_RELEASE_NAME: clamav-deployment
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}-clamav"
  HUSKY: 0

jobs:

  build_and_push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 #v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 #v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 #v6.16.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: ./clamav
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build_and_push
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: 'YAML poke: Set image location'
        uses: fjogeleit/yaml-update-action@b75e8a929eb61bff6b67a6114943c9468f0bd933 #v0.16.0
        with:
          valueFile: 'clamav/values.yaml'
          propertyPath: 'clamav.image'
          value: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          changes: |
            {
              "clamav.image": "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}",
              "clamav.tag": "${{ github.event.inputs.environment }}",
            }
          commitChange: false

      - name: Authenticate with OpenShift
        uses: redhat-actions/oc-login@5eb45e848b168b6bf6b8fe7f1561003c12e3c99d #v1.3
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          namespace: ${{ secrets.TOOLS_OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.TOOLS_OPENSHIFT_SERVICE_ACCOUNT_TOKEN }}
          insecure_skip_tls_verify: true

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./clamav \
            --namespace ${{ secrets.TOOLS_OPENSHIFT_NAMESPACE }} \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ needs.build_and_push.outputs.image_tag }}

      - name: Restart Pod after image update
        run: |
          oc rollout restart statefulset \
            --namespace ${{ secrets.TOOLS_OPENSHIFT_NAMESPACE }} \
            --selector=app.kubernetes.io/name=clamav
